# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HPDS-Data' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HPDS-Data
  platform :ios, '10.0'
  pod 'AWAREFramework', :git=>'https://github.com/tetujin/AWAREFramework-iOS.git'

end
